# Generated by Django 5.0.8 on 2024-09-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_produit',
            new_name='name_product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_produit',
            new_name='price_product',
        ),
    ]
