# Generated by Django 5.0.8 on 2024-09-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_name_produit_product_name_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_produit',
            new_name='id_product',
        ),
    ]
