name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./backend/Dockerfile  
        push: false
        tags: your-docker-image:latest

    - name: Deploy to PythonAnywhere
      env:
        PA_TOKEN: ${{ secrets.PYTHONANYWHERE_TOKEN }}
      run: |
        pip install pythonanywhere
        pa_autoconfigure_django.py --python=3.8 https://github.com/votre-nom/votre-repo.git
        curl -X POST \
          -H "Authorization: Token $PA_TOKEN" \
          https://www.pythonanywhere.com/api/v0/user/mlndiaye/webapps/mlndiaye.pythonanywhere.com/reload/