name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: false
        tags: your-django-app:latest

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Build Angular app
      working-directory: ./frontend
      run: |
        npm install
        npm run build --prod

    - name: Deploy to PythonAnywhere
      env:
        PA_TOKEN: ${{ secrets.PYTHONANYWHERE_TOKEN }}
      run: |
        pip install pythonanywhere
        pa_autoconfigure_django.py --python=3.10 https://github.com/mlndiaye/Projet-trans-boutique-hybride.git
        
        # Copier les fichiers du frontend build vers le dossier static du backend
        mkdir -p /home/mlndiaye/Projet-trans-boutique-hybride/backend/static/angular
        cp -r frontend/dist/* /home/mlndiaye/Projet-trans-boutique-hybride/backend/static/angular/
        
        # Recharger l'application
        curl -X POST \
          -H "Authorization: Token $PA_TOKEN" \
          https://www.pythonanywhere.com/api/v0/user/mlndiaye/webapps/mlndiaye.pythonanywhere.com/reload/